services:
  dev:
    build:
      context: ..  # project root
      dockerfile: docker/dev.Dockerfile
      args:
        - ANTHROPIC_BASE_URL=${ANTHROPIC_BASE_URL}
        - ANTHROPIC_AUTH_TOKEN=${ANTHROPIC_AUTH_TOKEN}
    container_name: storage-hub-dev
    stdin_open: true        # docker run -i
    tty: true               # docker run -t
    volumes:
      - ..:/storage-hub:rw    # mount full repo
      - cargo-cache:/usr/local/cargo/registry
      - target-cache:/storage-hub/target
    env_file:
      - .env
    working_dir: /storage-hub
    command: /bin/bash           # open interactive shell by default
    # Expose common node ports; change as needed during development
    ports:
      - "9944:9944"
      - "30333:30333"
      - "30334:30334"
      - "9615:9615"

volumes:
  cargo-cache:
  target-cache: 